### ISSUE TITLE
MongoDB/Morphia Support?

### ISSUE THREAD

**Issue by gpedro** [tlaukkan/vaadin-lazyquerycontainer#73]
is possible add support to the [MongoDB](https://github.com/mongodb/mongo-java-driver) / [Morphia](https://github.com/mongodb/morphia)?

**Comment by tlaukkan** [comment]
Hi

Thank you for bringing up interesting topic.

I have not been privileged to work with either MongoDb or Morphia but I can see two ways of implementing support for them.

1) If they have extensive enough support for JPA then it would be simply matter of configuring JPA and using EntityContainer class of LazyQueryContainer out of box.
2) Another option would be to write custom EntityQueryFactory and EntityQuery.

Should the JPA support be lacking I am happy to review and accept pull requests related to MongoDb and other NoSQL databases. Please note that it is easier and faster for me to handle pull requests if they contain single topic per pull request and no changes outside that scope.

Best regards,
Tommi
