### ISSUE TITLE
use case when size is indeterminate

### ISSUE THREAD

**Issue by carljmosca** [tlaukkan/vaadin-lazyquerycontainer#78]
Is there a value which can be returned by the org.vaadin.addons.lazyquerycontainer.Query.size implementation for the use case in which the actual value is not known?

**Comment by turgos** [comment]
We have this exact requirement on our project. Data is coming from an Rest API and API response is a Rest Page of 100 elements at a time. It only tells if the requested page is the last one or not and does not give info about the total number of elements. We need to change the size lazy as well.
Do you have any ETA when this could be available? Thank you in advance, Turgos.

**Comment by tlaukkan** [comment]
This is not currently in the scope of LQC but if you find a working solution a pull request is appreciated.
