### ISSUE TITLE
Vaadin Table not sortable via header click with LazyQueryContainer

### ISSUE THREAD

**Issue by mamuf** [tlaukkan/vaadin-lazyquerycontainer#81]
Hi, I found a strange behaviour of Table in combination with LazyQueryContainer. When I use, for example, the IndexedContainer from Vaadin and set Table's sortEnabled to true, header click sorts the container by selected column as expected. But when I replace the container with LazyQueryContainer with custom bean Query (via BeanQueryFactory), clicking on the table's header seems to do nothing at all. I can "fix" this by adding HeaderClickListener to the table and invoke the Table.sort() method myself but then the sorting indicators are not removed from the columns that are not sorted. 

I am not sure where the problem might be, I have tried to analyze and compare the code of LQC and IndexedContainer, compare implemented interfaces since Table behaviour is partially derived from what the container can do. I can't find anything that may be the source of this.

Note that I first encountered this issue when using the [FilteringTable addon by Teppo Kurki](https://vaadin.com/directory#!addon/filteringtable) but it behaves the same when I use the vanilla Table.

I am using Vaadin 7.5.6 and LQC addon 7.4.0.1 which includes the #71 fix sou this must be something different. I can write a small demo project if that helps. I only tried this in my work project.

**Comment by mamuf** [comment]
Ok, I have discovered that the LQC's implementation of `addContainerProperty(Object, Class, Object)` method sets internal sortable flag to false by default and that the LQC provides another method: `addContainerProperty(Object, Class, Object, boolean, boolean)` in which the last parameter is the sortable flag. So I could fix my problem now but I still think the default behaviour of the first method should be something like checking if givne property class implements `java.lang.Comparable`.

**Comment by cstenkes** [comment]
Hi, When I use Table backed with LQC container I can't see the sort indicator. The sorting seems working, but only for ascending. I can't make it work to show the sort indicator. I have set the sortEnable true for the table, and the LCQ factory is implements Sortable.

I use Vaadin v7.3.3 and LCQ  v7.6.1.3.

Please give a hint, if you have any idea.
