### ISSUE TITLE
Access data for other component than table?

### ISSUE THREAD

**Issue by stozk** [tlaukkan/vaadin-lazyquerycontainer#82]
Hi,

I'm just asking for my understanding:
Can I use the lazy query container to pull data for other components than a table?
Every example for any kind of datasource always uses just a table.

I want to pull data from a DB, where every entity is represented inside a small panel component,
which is arranged in a gridlayout.

So I'm wondering, if this is the right component to use for data access for this.

Thanks & BR

**Comment by tlaukkan** [comment]
Hi, you can use LQC for other components as well.
