### ISSUE TITLE
Add items to the end of a container\table

### ISSUE THREAD

**Issue by SirWayne** [tlaukkan/vaadin-lazyquerycontainer#83]
Hey,

is there a possiblity to add items to the end of a container\table?
In the LazyQueryView the item will always be added at index 0.

```java
 @Override
    public int addItem() {
        addedItems.add(0,item);
        if (itemIdList instanceof NaturalNumberIdsList) {
            itemIdList = null;
        }
        return addedItems.indexOf(item);
    }
```

So if i add many new items to a table, it will begin to flicker. In this case it's better to add item at the end like the IndexedContainer do it.

**Comment by tlaukkan** [comment]
Hi, there is no support for adding items in the end at the moment. If you implement such feature please create a pull request.
